### ISSUE TITLE
Up-to-date TODO list for per-interpreter GIL.

### ISSUE THREAD

**Issue by ericsnowcurrently** [ericsnowcurrently/multi-core-python#78]
Here's a rough TODO list, sort of in order (a lot can be done in parallel).

Note that most of these items fall out of Tools/c-analyzer/cpython/globals-to-fix.tsv.  (Run `./python Tools/c-analyzer/table-file.py Tools/c-analyzer/cpython/globals-to-fix.tsv` to get counts.)

* [ ] clarify next steps [with the steering council](https://github.com/python/steering-council/issues/103)
* immortal objects:
   + [ ]  connect with @eduardo-elizondo ([bpo-40255](https://bugs.python.org/issue40255), [gh-19474](https://github.com/python/cpython/pull/19474))
   + [ ] benchmark branch with all objects immortalized at end of runtime init
   + [ ] enumerate other strategies for getting back to performance neutral
   + [ ] prepare a contingency plan for if we don't end up with immortal objects
* c-analyzer
   + [ ] re-enable CI check to prevent addition of more globals
   + [ ] fix "c-analyzer.py data check" & add to CI
   + [ ] finish "c-analyzer.py data count"
* consolidating globals
   * [ ] drop `_Py_IDENTIFIER()` in extensions (or modify it to use a statically initialized str?)
   * [ ] (maybe?) move state from `PyInterpreterState`to `_PyRuntimeState`
   * [ ] statically init latin-1 chars
   * [ ] statically init currently cached str objects
   * [ ] deal with PyArg_Parser
   * [ ] statically init other immutables?
   * [ ] pull remaining objects into `_PyRuntimeState`
   * [ ] pull remaining state into `_PyRuntimeState`
* per-interpreter state
   * [ ] solve per-interpreter state for core/builtin static types (e.g. dynamic lookup for some attrs)
   * [ ] solve for extensions
   * [ ] make some vars atomic?
   * [ ] convert stdlib extensions to PEP 630 (see [bpo-40077](https://bugs.python.org/issue40077) & [the SC discussion](https://github.com/python/steering-council/issues/103))
* per-interpreter GIL
   * [ ] enforce restrictions on importing extensions...
   * [ ] finally: move some state/objects to `PyInterpreterState`
   * [ ] 💥 **move the GIL to `PyInterpreterState`** 💥

Other related items:
* PEP 554
* help numpy, cython, etc.
* PEP: add Public C-API as replacement for `_Py_IDENTIFIER()` (@zooba's staticstr?)

**Comment by ericsnowcurrently** [comment]
FYI, here's a recent breakdown of the remaining globals:

* core/builtins (651 total)
   + 298 static types (incl. 130 exception types)
   + 179 cached objects (e.g. str instances)
   + 57 other objects
   + 117 non-object (incl. 60 state)
* extension modules (605 total)
   + 78 static types
   + 317 cached objects (e.g. str instances)
   + 145 other objects
   + 65 non-object (incl. 29 state)

<details>
<summary>(the detailed breakdown)</summary>

```
./python Tools/c-analyzer/table-file.py Tools/c-analyzer/cpython/globals-to-fix.tsv
 --------------------------------------------------
  (365)       global objects to fix in core code
         119      static types
         130      builtin exception types
           9      singletons
   (98)           cached - initialized once
          39          manually cached PyUnicodeObject
          54          _PyArg_Parser (holds tuple of strings)
           1          holds strings
           4          other
    (9)           other
           7          initialized once
           2          state
 --------------------------------------------------
   (94)       global non-objects to fix in core code
   (29)           initialized/set once
           1          pre-allocated buffer
          13          during init
          15          lazy
   (20)           unlikely to change after init (or main thread)
          11          through C-API
           4          REPL
           5          handling C argv
   (45)           state
          15          allocator
           2          pre-allocated memory
           2          local buffer
           2          linked list
          24          other
 --------------------------------------------------
  (169)       global objects to fix in builtin modules
          22      modules
          49      static types
    (5)           non-static types - initialized once
           3          structseq types
           2          exception types
   (81)           cached - initialized once
          29          manually cached PyUnicodeOjbect
          52          _PyArg_Parser
   (12)           other
           6          initialized once
           6          state
 --------------------------------------------------
   (23)       global non-objects to fix in builtin modules
           8      initialized once
          15      state
 --------------------------------------------------
  (540)       global objects to fix in extension modules
          65      modules
          78      static types
   (34)           non-static types - initialized once
           3          structseq types
           6          heap types
          25          exception types
  (317)           cached - initialized once
          18          _Py_IDENTIFIER (global)
         149          _Py_IDENTIFIER (local)
           1          _Py_static_string
          12          manually cached PyUnicodeOjbect
         124          _PyArg_Parser
          13          other - during module init
   (46)           other
          31          initialized once
          15          state
 --------------------------------------------------
   (65)       global non-objects to fix in extension modules
   (36)           initialized once
           2          pre-allocated buffer
          34          other
          29      state
 --------------------------------------------------
(total: 1256)
```
</details>

**Comment by kumaraditya303** [comment]
statically init latin-1 chars is done https://bugs.python.org/issue46881
